name: CI

on:
  push:
    branches: [main]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v4
    
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: brunooliverserra
          password: Bloess@83
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            brunoserraoliveira/github_actions:v1
            brunoserraoliveira/github_actions:latest